steps: 
- name: 'gcr.io/google-samples/intro-to-krm/skaffold-mvn:latest'
  id: Deploy to Staging Cluster 
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone "https://github.com/$$GITHUB_USERNAME/cymbal-config"
    gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_CLUSTER_ZONE} --project ${PROJECT_ID} 
    skaffold run --profile=staging --default-repo="gcr.io/${PROJECT_ID}/cymbal-bank/${BRANCH_NAME}" --status-check --tail=false --force=true
  secretEnv: ['GITHUB_USERNAME']
substitutions:
  _CLUSTER_NAME: 'staging'
  _CLUSTER_ZONE: 'us-east1-b'
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-username/versions/latest
    env: 'GITHUB_USERNAME'
timeout: '1200s' #timeout - 20 minutes
options:
  machineType: 'E2_HIGHCPU_8'
